# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shortcut_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from . import resources


class Ui_ShortcutWidget(object):
    def setupUi(self, ShortcutWidget):
        ShortcutWidget.setObjectName("ShortcutWidget")
        ShortcutWidget.resize(300, 41)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ShortcutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.deleteButton = QtWidgets.QPushButton(ShortcutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.deleteButton.sizePolicy().hasHeightForWidth()
        )
        self.deleteButton.setSizePolicy(sizePolicy)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.editButton = QtWidgets.QPushButton(ShortcutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.editButton.sizePolicy().hasHeightForWidth()
        )
        self.editButton.setSizePolicy(sizePolicy)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        self.shortcutIcon = QtWidgets.QLabel(ShortcutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.shortcutIcon.sizePolicy().hasHeightForWidth()
        )
        self.shortcutIcon.setSizePolicy(sizePolicy)
        self.shortcutIcon.setStyleSheet("margin-left:25px")
        self.shortcutIcon.setText("")
        self.shortcutIcon.setPixmap(
            QtGui.QPixmap(":/ShortcutManager/icons/default-shortcut-desk.png")
        )
        self.shortcutIcon.setObjectName("shortcutIcon")
        self.horizontalLayout.addWidget(self.shortcutIcon)
        self.shortcutName = QtWidgets.QLabel(ShortcutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.shortcutName.sizePolicy().hasHeightForWidth()
        )
        self.shortcutName.setSizePolicy(sizePolicy)
        self.shortcutName.setObjectName("shortcutName")
        self.horizontalLayout.addWidget(self.shortcutName)

        self.retranslateUi(ShortcutWidget)
        QtCore.QMetaObject.connectSlotsByName(ShortcutWidget)

    def retranslateUi(self, ShortcutWidget):
        _translate = QtCore.QCoreApplication.translate
        ShortcutWidget.setWindowTitle(_translate("ShortcutWidget", "Form"))
        self.deleteButton.setText(_translate("ShortcutWidget", "Delete"))
        self.editButton.setText(_translate("ShortcutWidget", "Edit"))
        self.shortcutName.setText(_translate("ShortcutWidget", "shortcutName"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ShortcutWidget = QtWidgets.QWidget()
    ui = Ui_ShortcutWidget()
    ui.setupUi(ShortcutWidget)
    ShortcutWidget.show()
    sys.exit(app.exec_())
