# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/shortcut_manager_dialog_ui_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShortcutManagerDialog(object):
    def setupUi(self, ShortcutManagerDialog):
        ShortcutManagerDialog.setObjectName("ShortcutManagerDialog")
        ShortcutManagerDialog.resize(530, 397)
        self.verticalLayout = QtWidgets.QVBoxLayout(ShortcutManagerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(ShortcutManagerDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 510, 329))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.layout.setObjectName("layout")
        self.shorcutWidgetsContainer = QtWidgets.QVBoxLayout()
        self.shorcutWidgetsContainer.setObjectName("shorcutWidgetsContainer")
        self.layout.addLayout(self.shorcutWidgetsContainer)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.layout.addWidget(self.label_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.label = QtWidgets.QLabel(ShortcutManagerDialog)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(ShortcutManagerDialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(ShortcutManagerDialog)
        QtCore.QMetaObject.connectSlotsByName(ShortcutManagerDialog)

    def retranslateUi(self, ShortcutManagerDialog):
        _translate = QtCore.QCoreApplication.translate
        ShortcutManagerDialog.setWindowTitle(_translate("ShortcutManagerDialog", "Shortcut manager"))
        self.pushButton.setText(_translate("ShortcutManagerDialog", "Create shortcut"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ShortcutManagerDialog = QtWidgets.QDialog()
    ui = Ui_ShortcutManagerDialog()
    ui.setupUi(ShortcutManagerDialog)
    ShortcutManagerDialog.show()
    sys.exit(app.exec_())
