# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_shortcut_wizard.ui'
#
# Created: Sat Aug 02 13:43:29 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CreateShortcutWizard(object):
    def setupUi(self, CreateShortcutWizard):
        CreateShortcutWizard.setObjectName(_fromUtf8("CreateShortcutWizard"))
        CreateShortcutWizard.resize(427, 217)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CreateShortcutWizard.sizePolicy().hasHeightForWidth())
        CreateShortcutWizard.setSizePolicy(sizePolicy)
        CreateShortcutWizard.setModal(True)
        self.wizardPage1 = QtGui.QWizardPage()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wizardPage1.sizePolicy().hasHeightForWidth())
        self.wizardPage1.setSizePolicy(sizePolicy)
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wizardPage1)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet(_fromUtf8("margin:25px; font:15px;"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.label = QtGui.QLabel(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet(_fromUtf8("margin-left:15px"))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self._shortcutURI = QtGui.QLineEdit(self.wizardPage1)
        self._shortcutURI.setStyleSheet(_fromUtf8("margin-left:15px"))
        self._shortcutURI.setObjectName(_fromUtf8("_shortcutURI"))
        self.horizontalLayout.addWidget(self._shortcutURI)
        self._changeShortcutURI_Btn = QtGui.QPushButton(self.wizardPage1)
        self._changeShortcutURI_Btn.setObjectName(_fromUtf8("_changeShortcutURI_Btn"))
        self.horizontalLayout.addWidget(self._changeShortcutURI_Btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        CreateShortcutWizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.wizardPage2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.wizardPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet(_fromUtf8("margin:25px; font:15px;"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtGui.QLabel(self.wizardPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet(_fromUtf8("margin-left:15px"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self._shortcutName = QtGui.QLineEdit(self.wizardPage2)
        self._shortcutName.setStyleSheet(_fromUtf8("margin-left:15px"))
        self._shortcutName.setObjectName(_fromUtf8("_shortcutName"))
        self.verticalLayout.addWidget(self._shortcutName)
        CreateShortcutWizard.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setObjectName(_fromUtf8("wizardPage3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.wizardPage3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(self.wizardPage3)
        self.label_5.setStyleSheet(_fromUtf8("margin:25px; font:15px;"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_7 = QtGui.QLabel(self.wizardPage3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet(_fromUtf8("margin-left:15px"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self._shortcutIcon = QtGui.QLabel(self.wizardPage3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._shortcutIcon.sizePolicy().hasHeightForWidth())
        self._shortcutIcon.setSizePolicy(sizePolicy)
        self._shortcutIcon.setFrameShape(QtGui.QFrame.Box)
        self._shortcutIcon.setFrameShadow(QtGui.QFrame.Plain)
        self._shortcutIcon.setText(_fromUtf8(""))
        self._shortcutIcon.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ShortcutManager/icon.png")))
        self._shortcutIcon.setObjectName(_fromUtf8("_shortcutIcon"))
        self.horizontalLayout_2.addWidget(self._shortcutIcon)
        self.label_8 = QtGui.QLabel(self.wizardPage3)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self._chooseIcon_Btn = QtGui.QPushButton(self.wizardPage3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._chooseIcon_Btn.sizePolicy().hasHeightForWidth())
        self._chooseIcon_Btn.setSizePolicy(sizePolicy)
        self._chooseIcon_Btn.setObjectName(_fromUtf8("_chooseIcon_Btn"))
        self.horizontalLayout_2.addWidget(self._chooseIcon_Btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        CreateShortcutWizard.addPage(self.wizardPage3)

        self.retranslateUi(CreateShortcutWizard)
        QtCore.QMetaObject.connectSlotsByName(CreateShortcutWizard)

    def retranslateUi(self, CreateShortcutWizard):
        CreateShortcutWizard.setWindowTitle(QtGui.QApplication.translate("CreateShortcutWizard", "Create shortcut", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CreateShortcutWizard", "For what element it is necessary to create a shortcut?", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CreateShortcutWizard", "Enter element placement:", None, QtGui.QApplication.UnicodeUTF8))
        self._changeShortcutURI_Btn.setText(QtGui.QApplication.translate("CreateShortcutWizard", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CreateShortcutWizard", "How to call a shortcut?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CreateShortcutWizard", "Enter shortcut name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CreateShortcutWizard", "What icon the shortcut has to have?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("CreateShortcutWizard", "Icon by default the specified element:", None, QtGui.QApplication.UnicodeUTF8))
        self._chooseIcon_Btn.setText(QtGui.QApplication.translate("CreateShortcutWizard", "Choose another...", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
